name: Build EDR-Freeze (Windows)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup MSVC compiler
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build with cl.exe
        run: cl /EHsc /O2 EDR-Freeze.cpp /Fe:EDR-Freeze.exe

      - name: Upload artifact (EXE)
        uses: actions/upload-artifact@v3
        with:
          name: EDR-Freeze-exe
          path: EDR-Freeze.exe
